### ISSUE TITLE
v2.0.0 is not published

### ISSUE THREAD

**Issue by klische** [venturehacks/bai2#6]
v2.0.0 of the library is not published.

https://rubygems.org/gems/bai2

The optional parameter in the init is not available in v1.0.0, and was wondering why it kept erroring when passing that 2nd optional parameter.

Can you please publish v2?

**Comment by Sumukh** [comment]
cc: @kballenegger

**Comment by kballenegger** [comment]
@Sumukh — Hmm, is this something you need me for? Can I transfer ownership to the relevant person at AL. cc @mpdaugherty

**Comment by Sumukh** [comment]
`v2.0.1` and `v2.0.0` are now published
